export enum ActionTypes {
  ON_APP_LOAD = 'ON_APP_LOAD',
  ON_LOGIN = 'ON_LOGIN',
  SET_APP_INITIALIZED = 'APP_INITIALIZED',
  SET_APP_LOADING = 'SET_APP_LOADING',
  SET_APP_ERROR = 'SET_APP_ERROR',
  SET_APP_INFO = 'SET_APP_INFO',
  CLOSE_SNACKBAR = 'CLOSE_SNACKBAR',
  SET_USER_DATA = 'SET_USER_DATA',
  SET_USERS = 'SET_USERS',
  SET_MY_TODOS = 'SET_MY_TODOS',
  SET_DISCOVER_TODOS = 'SET_DISCOVER_TODOS',
  SET_FRIENDS_TODOS = 'SET_FRIENDS_TODOS',
  SET_NOTIFICATIONS = 'SET_NOTIFICATIONS',
  ON_ADD_TODO = 'ON_ADD_TODO',
  SET_COMPLETE_TODO_MODAL_OPEN = 'SET_COMPLETE_TODO_MODAL_OPEN',
  ON_FINISH_TODO = 'ON_FINISH_TODO',
  ON_LIKE_TODO = 'ON_LIKE_TODO',
};

interface ActionReturn<T> {
  type: string;
  payload: T;
}

export type Action<T> = (payload: T) => ActionReturn<T>;
export type ActionNoPayload = () => { type: string }
